### ISSUE TITLE
Database & Supabase Setup

### ISSUE THREAD

**Issue by mouimet-infinisoft** [mouimet-infinisoft/ibrain2024#1]
## Description:
Define and implement database schema, relationships.

## Tasks:
- [x] Set up Supabase
- [x] Define initial schema  for basic conversation. 
- [x] Implement tables and relationships
  - [x] conversations
  - [x] messages
