### ISSUE TITLE
LLM & API Integration

### ISSUE THREAD

**Issue by mouimet-infinisoft** [mouimet-infinisoft/ibrain2024#2]
## Description:
Implement core LLM functionality and API integration

## References:
[LLM Integration Guide](docs/llm/integration.md)

## Tasks:
- [x] Select appropriate LLM API
- [ ] Implement core task introspection
- [ ] Build prompt templates

**Comment by mouimet-infinisoft** [comment]
Article source to configure Bull Dashboard on NextJS
https://github.com/felixmosh/bull-board/issues/124
