### ISSUE TITLE
Voice and Text Interface Implementation

### ISSUE THREAD

**Issue by mouimet-infinisoft** [mouimet-infinisoft/ibrain2024#4]
## Description:
Create the primary user interaction interface

## References:
[Interface Design Specs](docs/ui/interface-specs.md)

## Tasks:
- [x] Set up Next.js and React interface
- [x] Integrate Web Speech API
- [x] Design UI/UX for input switching

**Comment by mouimet-infinisoft** [comment]
# Chat Feature Implementation Specification - Next.js 15

## Directory Structure
```
app
├── protected
│   ├── chat
│   │   ├── [conversationId]
│   │   │   ├── page.tsx                # Server Component: Individual chat view
│   │   │   ├── loading.tsx             # Loading UI
│   │   │   └── error.tsx              # Error UI
│   │   ├── components
│   │   │   ├── chat
│   │   │   │   ├── chat-input.tsx      # Client Component: Message input
│   │   │   │   ├── chat-stream.tsx     # Server Component: Streamed messages
│   │   │   │   ├── message-list.tsx    # Server Component: Messages container
│   │   │   │   └── message-item.tsx    # Server Component: Individual message
│   │   │   └── ui
│   │   │       ├── empty-state.tsx     # Server Component: Empty state
│   │   │       └── loading-skeleton.tsx # Loading UI components
│   │   ├── actions
│   │   │   └── chat-actions.ts         # Server Actions
│   │   ├── lib
│   │   │   ├── types.ts               # TypeScript types
│   │   │   ├── db.ts                  # Database utilities
│   │   │   └── ai.ts                  # AI model integration
│   │   └── page.tsx                   # Server Component: Chat home
│   └── layout.tsx                     # Protected layout (existing)
```

## Component Architecture

### Server Components

1. `page.tsx` (chat home)


2. `[conversationId]/page.tsx`


3. `chat-stream.tsx`


### Client Components (Minimal)

Only components that require user interaction are client components:

1. `chat-input.tsx`


### Server Actions

1. sendMessage(formData: FormData) 
2. createConversation()


## Database Schema (Supabase)

```sql
-- Conversations table
create table conversations (
  id uuid default uuid_generate_v4() primary key,
  user_id uuid references auth.users not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  last_message_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Messages table
create table messages (
  id uuid default uuid_generate_v4() primary key,
  conversation_id uuid references conversations on delete cascade not null,
  content text not null,
  role text not null check (role in ('user', 'assistant')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Message chunks for streaming
create table message_chunks (
  id uuid default uuid_generate_v4() primary key,
  conversation_id uuid references conversations on delete cascade not null,
  content text not null,
  role text not null check (role in ('assistant')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
```

## Key Technical Aspects

1. **Server-First Architecture**
   - Almost everything is a Server Component
   - Minimal client-side JavaScript
   - Uses Server Actions instead of API routes
   - Streaming responses from AI model

2. **Data Flow**
   - Server Components fetch data directly
   - Server Actions handle mutations
   - Real-time updates through server streaming
   - Automatic revalidation with `revalidatePath`

3. **Performance Optimizations**
   - Streaming UI with Suspense boundaries
   - Progressive enhancement
   - Optimistic updates where needed
   - Minimal client-side state

4. **UI Components Integration**
   - shadcn/ui components used server-side where possible
   - Tailwind for styling
   - Server-side rendered loading states

5. **Security**
   - Server-side validation
   - RLS policies
   - Server Actions for all mutations

## Implementation Phases

1. **Phase 1: Core Structure**
   - [x] Set up Server Components
   - [x]  Implement database schema
   - [x]  Basic message flow

2. **Phase 2: Streaming**
   - [x]  Implement message streaming
   - [x]  Add Suspense boundaries
   - [x]  Set up chunked responses

3. **Phase 3: UI Enhancement**
   - [x]  Add shadcn/ui components
   - [x]  Implement loading states
   - [x]  Error boundaries

Key Differences from Traditional Approach:
- No client-side state management (no Redux, Zustand, etc.)
- No API routes
- Minimal use of client components
- Heavy use of Server Components and Actions
- Streaming-first approach for real-time updates

**Comment by mouimet-infinisoft** [comment]
### Implementation Status & Architectural Changes

The first draft of the Voice and Text Interface implementation has been completed, with all core functionalities implemented including voice features. The implementation required some architectural adjustments from the initial specification due to technical constraints:

**Key Challenge Addressed:**
- Server Actions, while powerful, currently don't support returning Stream objects, limiting our ability to implement real-time streaming responses from the LLM
- This limitation required pivoting from the pure Server Actions approach to implementing a dedicated API endpoint capable of handling streaming responses

**Implementation Outcome:**
- Successfully implemented streaming functionality through a dedicated API endpoint that returns Stream objects from the LLM
- Voice interface implementation complete with both Text-to-Speech and Speech-to-Text capabilities
  - Basic recording functionality via record button
  - Audio playback support via play button
- Maintained core functionality while adapting the architecture to support real-time data streaming

The current implementation achieves all primary objectives, including text streaming and voice features. Future iterations will focus on refactoring and expanding the voice interface architecture for enhanced functionality.

Closing this issue as the first draft implementation is complete with all planned features. Further improvements and architectural enhancements will be tracked in separate issues.
